### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by QuagisCool** [monkeyman192/BoxBoyLevelEditor#18]
I am getting the error PS C:\Users\Admin\Downloads\BoxBoyLevelEditor-master (1)\BoxBoyLevelEditor-master> python MapEditor.py
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\BoxBoyLevelEditor-master (1)\BoxBoyLevelEditor-master\MapEditor.py", line 9, in <module>
    from map_formats.read_map import extract_map_data
  File "C:\Users\Admin\Downloads\BoxBoyLevelEditor-master (1)\BoxBoyLevelEditor-master\map_formats\read_map.py", line 3, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

Why? 

Also is this still being worked on?

**Comment by monkeyman192** [comment]
you need to do `pip install lxml` to get that library. Also, no, I haven't worked on this in many years sorry...

**Comment by QuagisCool** [comment]
Now it is saying this, File "C:\Users\Admin\Downloads\BoxBoyLevelEditor-master\BoxBoyLevelEditor-master\MapEditor.py", line 12, in <module>
    from MapCanvas import MapCanvas
  File "C:\Users\Admin\Downloads\BoxBoyLevelEditor-master\BoxBoyLevelEditor-master\MapCanvas.py", line 5, in <module>
    from PIL import Image, ImageTk
ModuleNotFoundError: No module named 'PIL'

**Comment by monkeyman192** [comment]
You also need to install PIL: `pip install Pillow`
